/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodos.PrimerDepartamental;

import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;
import metodos.Funcion;

/**
 *
 * @author Eduardo
 */
public class NewtonRaphson extends javax.swing.JFrame {

    DefaultTableModel newRapTabla;
    private Integer i = 0;
    private Double[] x;
    private Double[] err;
    private Integer c;
    private Double ec, id;
    private Double xin;
    private Integer redon;

    /**
     * Creates new form Eulier
     */
    public NewtonRaphson() {

        initComponents();
        creaColumna();
        x = new Double[50];
        err = new Double[50];

    }

    public void creaColumna() {
        newRapTabla = (DefaultTableModel) newRapTab.getModel();
        newRapTabla.addColumn("i");
        newRapTabla.addColumn("x(i)");
        newRapTabla.addColumn("Errr");
    }

    public void creaFila(Double i, Double x, Double err) {
        newRapTabla = (DefaultTableModel) newRapTab.getModel();

        Double[] fila = {i, x, err};
        newRapTabla.addRow(fila);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newRapBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newRapX0 = new javax.swing.JTextField();
        newRapC = new javax.swing.JTextField();
        newRapCalc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        newRapTab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("EULIER"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.POPUP);

        newRapBack.setText("Regresar");
        newRapBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRapBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Newton Raphson");

        jLabel2.setText("Dame inicio");

        jLabel3.setText("Dame cifras");

        newRapX0.setName(""); // NOI18N

        newRapCalc.setText("Calcular");
        newRapCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRapCalcActionPerformed(evt);
            }
        });

        newRapTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(newRapTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newRapX0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newRapC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(252, 252, 252)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newRapBack)
                                    .addComponent(newRapCalc))))
                        .addContainerGap(268, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRapX0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(newRapCalc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRapC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(newRapBack)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newRapBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRapBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_newRapBackActionPerformed

    private void newRapCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRapCalcActionPerformed
        xin = Double.parseDouble(newRapX0.getText());
        c = Integer.parseInt(newRapC.getText());
        x[0] = xin;
        redon = (c + 2);
        Double aux = (Math.pow(10, -c));
        ec = redondeo((0.5 * aux), redon);
        err[i] = 1.0;
        id = i * 1.0;
        creaFila(id, x[i], err[i]);

        while ((err[i] > ec)) {
            i++;
            x[i] = redondeo((x[i - 1] - (f(x[i - 1]) / fp(x[i - 1]))), redon);
            err[i] = redondeo(Math.abs((((x[i] - x[i - 1]) / x[i]))), redon);
            id = i * 1.0;
            creaFila(id, x[i], err[i]);

        }
    }//GEN-LAST:event_newRapCalcActionPerformed

    public double redondeo(double n, int d) {
        BigDecimal bigDecimal = new BigDecimal(n);
        bigDecimal = bigDecimal.setScale(d, BigDecimal.ROUND_HALF_EVEN);
        return bigDecimal.doubleValue();
    }

    Double f(Double x) {
        double f = redondeo(((Math.pow(x, 3)) - (4 * x) + 1), redon);
        return (Double) f;
    }

    Double fp(Double x) {
        double fp = redondeo(((3 * (Math.pow(x, 2))) - (4)), redon);
        return (Double) fp;
    }

    //<>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewtonRaphson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newRapBack;
    private javax.swing.JTextField newRapC;
    private javax.swing.JButton newRapCalc;
    private javax.swing.JTable newRapTab;
    private javax.swing.JTextField newRapX0;
    // End of variables declaration//GEN-END:variables
}
