/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodos.PrimerDepartamental;

import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;
import metodos.Funcion;

/**
 *
 * @author Eduardo
 */
public class RaizDos extends javax.swing.JFrame {
   DefaultTableModel raizTabla;
    
        
    /**
     * Creates new form Eulier
     */
    public RaizDos() {
        
        initComponents();
        creaColumna();
        

    }

    public void creaColumna(){
         raizTabla = (DefaultTableModel) raizTab.getModel();
         raizTabla.addColumn("i");
         raizTabla.addColumn("x(i)");
         raizTabla.addColumn("Errr");
    }
    
    public void creaFila(Double i, Double x, Double err){
        raizTabla = (DefaultTableModel) raizTab.getModel();
        
        Double[] fila = {i, x, err};
        raizTabla.addRow(fila);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eulierBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        raizX0 = new javax.swing.JTextField();
        raizC = new javax.swing.JTextField();
        eulierCalc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        raizTab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("EULIER"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.POPUP);

        eulierBack.setText("Regresar");
        eulierBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eulierBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Raíz De Dos");

        jLabel2.setText("Dame inicio");

        jLabel3.setText("Dame cifras");

        raizX0.setName(""); // NOI18N

        eulierCalc.setText("Calcular");
        eulierCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eulierCalcActionPerformed(evt);
            }
        });

        raizTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(raizTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(raizX0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(raizC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(eulierCalc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eulierBack))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raizX0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raizC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eulierCalc)
                    .addComponent(eulierBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eulierBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eulierBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_eulierBackActionPerformed

    private void eulierCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eulierCalcActionPerformed
        Double xin = redondeo(Double.parseDouble(raizX0.getText()),4);
        Integer c = Integer.parseInt(raizC.getText());
        Double[] err = new Double [50];
        Double[] x = new Double [50];
        Integer i = 0;
        Double ec, id;
        Integer redon;
       
        x[0] = xin;
        redon = (c + 2);
        Double aux = (Math.pow(10, -c));
        ec =  redondeo((0.5 * aux), redon);
        err[i] = 1.0;
        id = i*1.0;
        creaFila( id , x[i], err[i]);
        while ((err[i] > ec)) {
            i++;
            x[i] = redondeo((0.5*((x[i-1] +2 / x[i-1]))),redon);
            err[i] = redondeo(Math.abs((((x[i]-x[i-1]) / x[i]))),redon);
            id = i *1.0;
            creaFila(id, x[i], err[i]);
        }
  
  
    }//GEN-LAST:event_eulierCalcActionPerformed

     public double redondeo(double n, int d){
          BigDecimal bigDecimal = new BigDecimal(n);
          bigDecimal = bigDecimal.setScale(d, BigDecimal.ROUND_HALF_UP);
          return bigDecimal.doubleValue();
     }

    //<>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaizDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaizDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaizDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaizDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaizDos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eulierBack;
    private javax.swing.JButton eulierCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField raizC;
    private javax.swing.JTable raizTab;
    private javax.swing.JTextField raizX0;
    // End of variables declaration//GEN-END:variables
}
