/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodos.PrimerDepartamental;

import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class ReglaFalsa extends javax.swing.JFrame {

    DefaultTableModel reglaFalsaTabla;
   Integer redon = 0;

    /**
     * Creates new form Eulier
     */
    public ReglaFalsa() {

        initComponents();
        creaColumna();

    }

    public void creaColumna() {
        reglaFalsaTabla = (DefaultTableModel) reglaFalsaTab.getModel();
        reglaFalsaTabla.addColumn("i");
        reglaFalsaTabla.addColumn("a");
        reglaFalsaTabla.addColumn("x(i)");
        reglaFalsaTabla.addColumn("b");
        reglaFalsaTabla.addColumn("f(a)");
        reglaFalsaTabla.addColumn("f(x(i))");
        reglaFalsaTabla.addColumn("f(b)");
        reglaFalsaTabla.addColumn("Error");
    }

    public void creaFila(Double i, Double a, Double x, Double b, Double fa, Double xi, Double fb, Double err) {
        reglaFalsaTabla = (DefaultTableModel) reglaFalsaTab.getModel();

        Double[] fila = {i, a, x, b, fa, xi, fb, err};
        reglaFalsaTabla.addRow(fila);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reglaFalsaBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reglaFalsaA = new javax.swing.JTextField();
        reglaFalsaB = new javax.swing.JTextField();
        reglaFalsaC = new javax.swing.JTextField();
        reglaFalsaCalc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reglaFalsaTab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("EULIER"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.POPUP);

        reglaFalsaBack.setText("Regresar");
        reglaFalsaBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reglaFalsaBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Regla Falsa");

        jLabel2.setText("Dame \"a\"");

        jLabel3.setText("Dame \"b\"");

        jLabel4.setText("Dame \"c\"");

        reglaFalsaA.setName(""); // NOI18N

        reglaFalsaCalc.setText("Calcular");
        reglaFalsaCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reglaFalsaCalcActionPerformed(evt);
            }
        });

        reglaFalsaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(reglaFalsaTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(reglaFalsaA, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(reglaFalsaB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reglaFalsaC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(reglaFalsaCalc)
                                .addGap(78, 78, 78)
                                .addComponent(reglaFalsaBack)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reglaFalsaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reglaFalsaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reglaFalsaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reglaFalsaBack)
                    .addComponent(reglaFalsaCalc))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reglaFalsaBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reglaFalsaBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_reglaFalsaBackActionPerformed

    private void reglaFalsaCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reglaFalsaCalcActionPerformed
        Double[] x = new Double[50];
        Double[] err = new Double[50];
        Double id;
        Double a = Double.parseDouble(reglaFalsaA.getText());
        Double b = Double.parseDouble(reglaFalsaB.getText());
        Integer c = Integer.parseInt(reglaFalsaC.getText());
        redon = (c + 2);
        Double aux = (Math.pow(10, -c));
        Double ec =  redondeo((0.5 * aux), redon);
        Integer i = 0;
        err[i] = 1.0;
        //x[i] = redondeo(((a + b) / 2),redon);
        x[i] = redondeo((((a*f(b)) - (f(a)*b)) / (f(b)-f(a))),redon);
        id = i*1.0;
        creaFila(id, a, x[i], b, f(a), f(x[i]), f(b), err[i]);
        while ((err[i] > ec)) {
            if (((f(x[i]) * f(a)) < 0)) {
                b = redondeo(x[i],redon);
            }
            else {
                a = redondeo(x[i],redon);
            }
            i++;
            x[i] = redondeo((((a*f(b)) - (f(a)*b)) / (f(b)-f(a))),redon);
            err[i] = redondeo((Math.abs((((x[i]-x[i-1]) / x[i])))),redon);
            id = i*1.0;
            creaFila(id, a, x[i], b, f(a), f(x[i]), f(b), err[i]);
        }
    }//GEN-LAST:event_reglaFalsaCalcActionPerformed

     Double f(Double x) {
        double f = redondeo(((Math.pow(x, 3))- (4 * x) + 1),redon);
        return (Double) f;
    }
    public double redondeo(double n, int d) {
        BigDecimal bigDecimal = new BigDecimal(n);
        bigDecimal = bigDecimal.setScale(d, BigDecimal.ROUND_HALF_EVEN);
        return bigDecimal.doubleValue();
    }

    //<>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReglaFalsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reglaFalsaA;
    private javax.swing.JTextField reglaFalsaB;
    private javax.swing.JButton reglaFalsaBack;
    private javax.swing.JTextField reglaFalsaC;
    private javax.swing.JButton reglaFalsaCalc;
    private javax.swing.JTable reglaFalsaTab;
    // End of variables declaration//GEN-END:variables
}
