/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodos.SegundoDepartamental;

import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class GaussSeidel extends javax.swing.JFrame {

    DefaultTableModel gaussSeidTabla;
    private Integer i = 0;
    private Double[] x, y, z;
    private Double[] ex, ey, ez;
    private Double b1, b2, b3;
    private Double a11, a12, a13;
    private Double a21, a22, a23;
    private Double a31, a32, a33;
    private Integer c;
    private Double ec, id;
    private Integer redon;

    /**
     * Creates new form Eulier
     */
    public GaussSeidel() {

        initComponents();
        creaColumna();
        x = new Double[50];
        ex = new Double[50];
        y = new Double[50];
        ey = new Double[50];
        z = new Double[50];
        ez = new Double[50];

    }

    public void creaColumna() {
        gaussSeidTabla = (DefaultTableModel) gaussSeidTab.getModel();
        gaussSeidTabla.addColumn("i");
        gaussSeidTabla.addColumn("x(i)");
        gaussSeidTabla.addColumn("y(i)");
        gaussSeidTabla.addColumn("z(i)");
        gaussSeidTabla.addColumn("ex");
        gaussSeidTabla.addColumn("ey");
        gaussSeidTabla.addColumn("ez");
    }

    public void creaFila(Double i, Double x, Double y, Double z, Double ex, Double ey, Double ez) {
        gaussSeidTabla = (DefaultTableModel) gaussSeidTab.getModel();

        Double[] fila = {i, x, y, z, ex, ey, ez};
        gaussSeidTabla.addRow(fila);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gaussSeidBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gaussSeidA11 = new javax.swing.JTextField();
        gaussSeidA12 = new javax.swing.JTextField();
        gaussSeidA13 = new javax.swing.JTextField();
        gaussSeidCalc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gaussSeidTab = new javax.swing.JTable();
        gaussSeidB1 = new javax.swing.JTextField();
        gaussSeidA21 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gaussSeidA22 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gaussSeidA23 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gaussSeidB2 = new javax.swing.JTextField();
        gaussSeidA31 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gaussSeidA32 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gaussSeidA33 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        gaussSeidC = new javax.swing.JTextField();
        gaussSeidB3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("EULIER"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.POPUP);

        gaussSeidBack.setText("Regresar");
        gaussSeidBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaussSeidBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Gauss Seidel");

        jLabel2.setText("x   +");

        jLabel3.setText("y   + ");

        jLabel4.setText("z   =");

        gaussSeidA11.setName(""); // NOI18N

        gaussSeidCalc.setText("Calcular");
        gaussSeidCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaussSeidCalcActionPerformed(evt);
            }
        });

        gaussSeidTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gaussSeidTab);

        gaussSeidA21.setName(""); // NOI18N

        jLabel5.setText("x   +");

        jLabel6.setText("y   + ");

        jLabel7.setText("z   =");

        gaussSeidA31.setName(""); // NOI18N

        jLabel8.setText("x   +");

        jLabel9.setText("y   + ");

        jLabel10.setText("z   =");

        jLabel11.setText("Dame \"c\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(gaussSeidCalc)
                                .addGap(86, 86, 86)
                                .addComponent(gaussSeidBack)
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gaussSeidA11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gaussSeidA12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gaussSeidA13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(gaussSeidB1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gaussSeidA21, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gaussSeidA22, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gaussSeidA23, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(gaussSeidB2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gaussSeidA31, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gaussSeidC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gaussSeidA32, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gaussSeidA33, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(gaussSeidB3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel11)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gaussSeidA11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaussSeidA12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaussSeidA13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(gaussSeidB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gaussSeidA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaussSeidA22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaussSeidA23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(gaussSeidB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gaussSeidA31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaussSeidA32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaussSeidA33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(gaussSeidB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gaussSeidCalc)
                            .addComponent(gaussSeidC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gaussSeidBack))))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gaussSeidBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaussSeidBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_gaussSeidBackActionPerformed

    private void gaussSeidCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaussSeidCalcActionPerformed
        c= Integer.parseInt(gaussSeidC.getText());
        a11 = Double.parseDouble(gaussSeidA11.getText());
        a12 = Double.parseDouble(gaussSeidA12.getText());
        a13 = Double.parseDouble(gaussSeidA13.getText());
        b1 = Double.parseDouble(gaussSeidB1.getText());
        a21 = Double.parseDouble(gaussSeidA21.getText());
        a22 = Double.parseDouble(gaussSeidA22.getText());
        a23 = Double.parseDouble(gaussSeidA23.getText());
        b2 = Double.parseDouble(gaussSeidB2.getText());
        a31 = Double.parseDouble(gaussSeidA31.getText());
        a32 = Double.parseDouble(gaussSeidA32.getText());
        a33 = Double.parseDouble(gaussSeidA33.getText());
        b3 = Double.parseDouble(gaussSeidB3.getText());
        x[0] = y[0] = z[0] = 0.0;
        ex[0] = ey[0] = ez[0] = 0.0;
        redon = (c + 2);
        Double aux = (Math.pow(10, -c));
        ec = redondeo((0.5 * aux), redon);
        id = i * 1.0;
        creaFila(id, x[i], y[i], z[i], ex[i], ey[i], ez[i]);
        do {
            i++;
            x[i] = redondeo(((b1 - (a12 * y[i - 1]) - (a13 * z[i - 1])) / a11), redon);
            y[i] = redondeo(((b2 - (a21 * x[i - 1]) - (a23 * z[i - 1])) / a22), redon);
            z[i] = redondeo(((b3 - (a31 * x[i - 1]) - (a32 * y[i - 1])) / a33), redon);
            ex[i] = redondeo(Math.abs((x[i] - x[i - 1]) / x[i]), redon);
            ey[i] = redondeo(Math.abs((y[i] - y[i - 1]) / y[i]), redon);
            ez[i] = redondeo(Math.abs((z[i] - z[i - 1]) / z[i]), redon);
            id = i * 1.0;
            creaFila(id, x[i], y[i], z[i], ex[i], ey[i], ez[i]);
        } while ((ec < ex[i]) || (ec < ey[i]) || (ec < ez[i]));
    }//GEN-LAST:event_gaussSeidCalcActionPerformed

    public double redondeo(double n, int d) {
        BigDecimal bigDecimal = new BigDecimal(n);
        bigDecimal = bigDecimal.setScale(d, BigDecimal.ROUND_HALF_EVEN);
        return bigDecimal.doubleValue();
    }

    //<>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GaussSeidel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gaussSeidA11;
    private javax.swing.JTextField gaussSeidA12;
    private javax.swing.JTextField gaussSeidA13;
    private javax.swing.JTextField gaussSeidA21;
    private javax.swing.JTextField gaussSeidA22;
    private javax.swing.JTextField gaussSeidA23;
    private javax.swing.JTextField gaussSeidA31;
    private javax.swing.JTextField gaussSeidA32;
    private javax.swing.JTextField gaussSeidA33;
    private javax.swing.JTextField gaussSeidB1;
    private javax.swing.JTextField gaussSeidB2;
    private javax.swing.JTextField gaussSeidB3;
    private javax.swing.JButton gaussSeidBack;
    private javax.swing.JTextField gaussSeidC;
    private javax.swing.JButton gaussSeidCalc;
    private javax.swing.JTable gaussSeidTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
